const animal = {
    imgIntro: "",
    altImgIntro: "",
    introTitle: "",
    //Todos os textos que tiverem quebra de linha devem estar entre ` ` para não dar erro no código
    introText: "",
    generalInformationText: ``,
    imgYouNeedToKnow: "",
    altImgYouNeedToKnow: "",
    lifetimeText: ``,
    estimatedPrice: ``,
    personality: ``,
    adaptationWithHumans: ``,
    physicalCharacteristics: ``,
    necessaryCareText: ``,
    imgProduct1: "",
    altImgProduct1: "",
    textImageProduct1: ``,
    imgProduct2: "",
    altImgProduct2: "",
    textImageProduct2: ``,
    imgProduct3: "",
    altImgProduct3: "",
    textImageProduct3: ``,
    curiosityTittle1: ``,
    curiosityText1: ``,
    curiosityTittle2: ``,
    curiosityText2: ``,
    curiosityTittle3: ``,
    curiosityText3: ``,
    curiosityTittle4: ``,
    curiosityText4: ``,
}

export default animal;