const PeriquitoObj = {
  imgIntro: "/images/pag_periquito_intro.png",
  altImgIntro: "Imagem periquito Intro",
  introTitle: "periquito",
  introText: `Periquito é o nome comum de várias espécies pertencentes à família Psittacidae que se alimenta essencialmente de sementes. Uma das características mais marcantes do Periquito são suas penas pontudas na cauda e suas cores vibrantes. Os Periquitos são aves sociáveis e brincalhões que precisam de um ambiente seguro, espaçoso, confortável e limpo para se manterem felizes e estimulados.`,
  generalInformationText: `Os Periquitos são amplamente escolhidos como pássaros de estimação devido à sua personalidade dócil e companhia agradável. Além de suas belas cores, são conhecidos por sua inteligência, independência e capacidade de interação. São ativos e gostam de receber atenção, podendo desenvolver laços afetivos fortes com seus tutores. Adoram atividades e brincadeiras que os mantêm ocupados em seu ambiente. O pilar da alimentação do Periquito deve ser ração específica para Periquitos e, como complemento, sirva petiscos em forma de frutas, vegetais e algumas sementes.`,
  imgYouNeedToKnow: "/images/pag_periquito_info.png",
  altImgYouNeedToKnow: "Imagem periquito info",
  lifetimeText: `Em média de 5 a 8 anos.`,
  estimatedPrice: `Pode variar entre R$20,00 a R$100,00.`,
  personality: `Inteligentes, independentes, harmoniosos.`,
  adaptationWithHumans: `Podem ser dóceis e afetivos.`,
  physicalCharacteristics: `Os periquitos têm penas coloridas e variadas`,
  necessaryCareText: `É essencial evitar alimentos prejudiciais como carne, tomate, alface, abacate, chocolate, cafeína e álcool, que podem causar graves problemas de saúde nos Periquitos. Eles preferem viver em pares para companhia e interação adequadas. Os Periquitos são brincalhões e podem desenvolver laços fortes com seus tutores, mas é importante incentivar brincadeiras e exercícios para sua saúde e felicidade. Eles geralmente cuidam da própria higiene, mas é importante fornecer acessórios como banheira e poleiros. Observar o comportamento é crucial para detectar problemas de saúde precocemente e buscar orientação veterinária quando necessário. E sempre manter o ambiente limpo. Alguns cuidados importantes para ter com um Periquito incluem fornecer uma gaiola espaçosa, uma dieta balanceada de sementes, frutas e vegetais, água fresca diariamente, higiene regular da gaiola, socialização e interação com o pássaro, além de visitas veterinárias regulares para exames de saúde.`,
  imgProduct1: "/images/racao_periquito_nutropica.png",
  altImgProduct1: "NuTrópica - Ração para Periquitos",
  textImageProduct1: `NuTrópica - Ração para Periquitos`,
  imgProduct2: "/images/racao_periquito_CEDAN.png",
  altImgProduct2: "CEDAN Rações - Ração para Periquitos",
textImageProduct2: `CEDAN Rações - Ração para Periquitos`,      
  imgProduct3: "/images/racao_periquito_melodiaPet.png",
    altImgProduct3: "MelodiaPet - Ração para Periquitos",
  textImageProduct3: "MelodiaPet - Ração para Periquitos", 
  curiosityTittle1: "IDENTIFICAÇÃO",
  curiosityText1: "A pequena região carnosa sobre o bico do Periquito é conhecida como “carúncula” e pode te ajudar a determinar o sexo do seu pássaro; machos apresentam carúncula em tons de azul, enquanto a carúncula das fêmeas é avermelhada ou marrom.",
  curiosityTittle2: "COLETIVIDADE",
  curiosityText2: "Periquitos são aves sociais e gostam de viver em grupos. Eles demonstram comportamentos de interação e comunicação entre si e com seus tutores.",
  curiosityTittle3: "HIGIENE",
  curiosityText3: "Os Periquitos são meticulosos em relação à sua higiene pessoal e passam uma parte significativa do tempo cuidando de suas penas e bico.",
  curiosityTittle4: "PÉS",
  curiosityText4: "Periquitos têm quatro dedos, dois dos quais estão voltados para a frente e dois voltados para trás. Isso os ajuda a ficar firmes em poleiros ou galhos. Os pés de um periquito podem dizer muito sobre a saúde da ave. Pés escamosos podem ser um sinal de parasitas ou deficiência nutricional.",
};
export default PeriquitoObj;